{ lib, modulesPath, ... }:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    # Uuhhhh autogenerated in the image probably?
    device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
    fsType = "ext4";
  };
  fileSystems."/boot/firmware" = {
    # Some magic from the image as well.
    device = "systemd-1";
    fsType = "autofs";
  };

  nixpkgs.hostPlatform = "aarch64-linux";
}
